[connections.snowflake]
account = "NDNVCXC-AHB95542"
user = "briggschristie"
password = "3232.SWim"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
